apiVersion: apps/v1
kind: Deployment
metadata:
  name: blog-server
  annotations:
    ve-weiyi/ve-admin-store: backend
    github: "https://github.com/ve-weiyi/ve-admin-store.git"
    app.kubernetes.io/version: 0.0.1
  labels:
    app: blog-server
    version: blog-vue3
spec:
  replicas: 1
  selector:
    matchLabels:
      app: blog-server
      version: blog-vue3
  template:
    metadata:
      labels:
        app: blog-server
        version: blog-vue3
    spec:
      containers:
        - name: ve77-container
          image: registry.cn-hangzhou.aliyuncs.com/blog/server:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 9999
              name: http
          volumeMounts:
            - mountPath: /go/src/github.com/ve-weiyi/ve-admin-store/server/config.docker.yaml
              name: config
              subPath: config.yaml
            - mountPath: /etc/localtime
              name: localtime
          resources:
            limits:
              cpu: 1000m
              memory: 2000Mi
            requests:
              cpu: 100m
              memory: 200Mi
          livenessProbe:
            failureThreshold: 1
            periodSeconds: 5
            successThreshold: 1
            tcpSocket:
              port: 9999
            timeoutSeconds: 1
          readinessProbe:
            failureThreshold: 3
            initialDelaySeconds: 30
            periodSeconds: 5
            successThreshold: 1
            tcpSocket:
              port: 9999
            timeoutSeconds: 1
          startupProbe:
            failureThreshold: 40
            periodSeconds: 5
            successThreshold: 1
            tcpSocket:
              port: 9999
            timeoutSeconds: 1
      #imagePullSecrets:
      #  - name: docker-registry
      volumes:
        - name: localtime
          hostPath:
            path: /etc/localtime
        - name: config
          configMap:
            name: config.yaml
